### ISSUE TITLE
use with ESP 12e module.

### ISSUE THREAD

**Issue by Biker1bob** [mecparts/RetroWiFiModem#2]
Wanted to ask, but I cannot find any way to contact you. I could use your firmware with an ESP 12e module by making sure the pin out is correct?  
When I try and use your code in Adruino IDE it says there is a missing ESP_EEPROM.h .. now I have done this with a FLASHER and .bin but not with the IDE .. is that something it finds once I choose the board? 
Sorry for using the issues page.. but could not contact you otherwise.

**Comment by mecparts** [comment]
I can't think of any reason off the top of my head why you couldn't make a bare ESP12e module work with the firmware.

As for the missing ESP_EEPROM.h... did you install the library?

**Comment by Biker1bob** [comment]
NodeMCU V3 Lua ESP8266 is the exact module, so I have the pinouts right there. I have programmed Zimodem. but its setup for a C64.. you have made specific changes for RS232. I would like to try and run the LEDs off the signal pins - to a resistor and then to LEDS in a old plastic modem case I have. Should work I think.

**Comment by Biker1bob** [comment]
![12e](https://user-images.githubusercontent.com/33105915/117355395-8546f900-ae80-11eb-97c8-327d003e9a49.jpg)

**Comment by mecparts** [comment]
A NodeMCU board? I don't imagine you'll have many problems with that. Just check how the pins are mapped and add the mappings to RetroWifiModem.h. It wouldn't surprise me if they're exactly the same as the D1 Mini; the original D1 was the odd duck as I recall.

**Comment by Biker1bob** [comment]
Do I need to change the name in the file  #include NodeMCU?  In order to compile and test do I need the board plugged in? 

Not getting far with Arduno IDE

James

**Comment by mecparts** [comment]
No, as it says in the readme, and as I said in an earlier message, all you should have to do is to add the correct pin mapping for your board in the RetroWifiModem.h file.

**Comment by Biker1bob** [comment]
guess I am not getting it.. I dont know how to get it to accept the .h files it cannot find.

**Comment by mecparts** [comment]
Your issues seem to be with the IDE rather than the firmware, but... I imagine you haven't installed the libraries you need. If this is your first time using the Arduino IDE, perhaps you'd do better starting with a simpler example to get your feet wet, and then working your way up.

**Comment by Biker1bob** [comment]
Thanks for your project I'll see what I can figure out.

**Comment by DRF-Solutions** [comment]
@Biker1bob Did you manage to get this working? I too am using the same board as you and ran into the same issue.
I managed to get libraries installed, and now get errors at compile stating the below.
I did also try changing the #ifdef ARDUINO_ESP8266_NODEMCU, to no avail...

> RetroWiFiModem:41:12: error: 'RI' was not declared in this scope; did you mean 'PI'?
>    41 |    pinMode(RI, OUTPUT);
>       |            ^~
>       |            PI
> RetroWiFiModem:42:12: error: 'DCD' was not declared in this scope
>    42 |    pinMode(DCD, OUTPUT);
>       |            ^~~
> RetroWiFiModem:43:12: error: 'DSR' was not declared in this scope
>    43 |    pinMode(DSR, OUTPUT);
>       |            ^~~
> RetroWiFiModem:44:17: error: 'TXEN' was not declared in this scope
>    44 |    digitalWrite(TXEN, HIGH);     // continue disabling TX until
>       |                 ^~~~
> exit status 1
> 'DCD' was not declared in this scope

**Comment by DRF-Solutions** [comment]
I think the issue is a certain library has been used, but the exact library used hasn't been mentioned or documented anywhere - making this project useless to anyone who doesn't already have that library installed.

@mecparts, can you please advise which libraries you have installed that are supporting this project?

Thanks

**Comment by mecparts** [comment]
I would have thought that the #includes <...> in the main sketch file would have made the libraries used pretty clear. And the only library used that isn't included with the standard ESP8266 install is ESP_EEPROM. Which has nothing to do with defining the I/O pins, by the way. As stated in the README file:

> If you're just using the software and not the PCB, there's no reason you couldn't use another kind of ESP8266 board; I used a D1 R1 myself when I was developing the modem. You'd just need to **add pin definitions for your board in RetroWiFiModem.h**.

**Comment by Biker1bob** [comment]
> @Biker1bob Did you manage to get this working? I too am using the same board as you and ran into the same issue.

No I have no luck using Arduino IDE or other programmers. I was able to get zimodem in a .bin which uploaded fine. I have been using my esp8266 wimodem for a month now.

Good luck.
