### ISSUE TITLE
Question about PCB and front panel labels

### ISSUE THREAD

**Issue by sofakng** [mecparts/RetroWiFiModem#3]
This is a fantastic project and I absolutely love the design!

Do you have the gerber files so I can order a PCB?

Also, how did you make the front panel piece with the signal labels?

**Comment by mecparts** [comment]
I'm glad to hear you like my little pandemic project. I've built (and use daily) two of them and am even thinking of putting together a third for another retro computer I'm bringing back to life.

As a pandemic project (i.e. "build it on the cheap with what I have on hand as much as possible") I went low tech on the PCB construction, so I never made Gerber files. Printed off the design on a sheet of that blue 'Press-n-Peel' transfer film, ironed it onto some copper clad board, etched it in an ammonium persulfate solution out on the deck on a hot summer day, drilled and trimmed it. As I said, low tech. But all done with stuff that I had from projects long ago.

Though... I see there's a place offering free PCBs up to 100mm x 150mm now. Maybe I should think about making some Gerbers and getting some boards made. I'd know then if the Gerbers were actually right and could put them up. It's worth looking into (I have visions of the "free" PCBs coming with a 50 buck customs clearing charge from the courier!).

If you look closely at the front panel picture, you can see a change in texture on the 3D printed panel just below the midline of the case. That's a piece of scotch tape, which is holding a piece of transparency film. I picked a font that looked good to me, used a table to get the spacing even, printed the letters on the film, cut it down to size and taped it on. Once again, low tech, cheap, but it works!

**Comment by sofakng** [comment]
Thanks so much for the reply!  I've actually purchased a used Hayes 1200 modem to use for this project but then I also forgot about the metal body and wireless signal.

What is the place offering free PCBs?  I've ordered from JLCPCB and it's extremely cheap, but the shipping is expensive.

If you decide to create some gerbers I'd love to give them a try and thanks again for all the information!

**Comment by mecparts** [comment]
It's called ALLPCB. I've only taken the briefest of looks at it; I've just got too many balls in the air right now. If it does turn out that it's really free I know I won't be able to stop myself from sitting down, figuring out the gerbers and getting some boards made to check if I've done them right.

**Comment by sofakng** [comment]
That's really interesting.  It sells one coupon per month per user for the free PCB and free shipping.

One last question ... what is the purpose of the 74HCT245 and 74HC32 chips?  I see they connect to the LEDs?

**Comment by mecparts** [comment]
The side facing LEDs are older items and need a fair bit more current than today's LEDs. The 245 was put in to supply that current w/o overtaxing the 8266s outputs (and why a 245 transceiver rather than say a 244 buffer? I had them on hand). As for the 32 quad OR gate, I'll just let the README speak for itself:

> The only major addition to the hardware during development was an OR gate on the serial output from the ESP8266. On startup, the ESP8266 sends out some debug information (at an oddball baud rate) through the serial port. It shows up as garbage characters to whatever's hooked up to the serial port. It annoyed me enough that I fed the Tx signal through the OR gate, with the other input hooked up to an output pin that I could count on remaining high (thereby masking off the Tx signal) until after the sketch had started and set it low.

**Comment by sofakng** [comment]
Thanks again so much for the help!
