### ISSUE TITLE
AT$AE no longer works & mDNS not broadcasting

### ISSUE THREAD

**Issue by SanguineBrah** [mecparts/RetroWiFiModem#4]
First, thanks for publishing this project. I had a ton of fun putting it together.

I have three modems built - the first was flashed in May of 2021 and the other two in August. It seems that the two more recent modems are showing issues that the earlier one does not:

- The auto exec function seems to be broken. No matter what it is set to, the modem always returns ERROR on power on/ATZ.
- They connect to wifi okay, can be pinged by using their IP address, however they do not broadcast on mDNS and do not show up in the Arduino IDE. I have confirmed this using Bonjour Browser, which shows several broadcasts from my media server but nothing from the modem. The modem from May shows up as it should however.

I've also desoldered and reflashed one of the newer modems with a build that was compiled today and can confirm that both issues are still showing.

Since the code hasn't really changed very much, I feel like this must be a problem with the libraries.

**Comment by mecparts** [comment]
A cursory look at open issues in the ESP8266 core reveals that TPTB apparently [broke something in mDNS](https://github.com/esp8266/Arduino/issues/8344) last year and that they're going to look at it in their next sprint - whenever that is. The ESP8266 core being slightly snafu'd isn't something I can do much about. I haven't updated my core in ages, on the "if it isn't broken, don't break it" principle. AT$AE still works fine for me, as does mDNS as you can see below.

![image](https://user-images.githubusercontent.com/2958269/150869380-554590e9-d7b8-4e05-b965-8461569946c5.png)

All I can think of to do from my end is to add the bin file that gets uploaded to the repository. You'll have to work out on your own how to manually upload that; in my ancient core there's a Python program called *espota.py* in the esp8266/tools directory tree that does the job. I make no assumptions that they haven't deleted/renamed/moved it in the current core.

**Comment by SanguineBrah** [comment]
Thanks, a working bin will at least get me up and running again until the issue is resolved. Unfortunately, I tried espota.py already following advice in [this thread](https://forum.arduino.cc/t/ota_mode-no-network-port-is-shown/552931/42) and didn't have much luck but I have a desoldering station so it won't be too traumatising to pull the module again and reflash by usb.

**Comment by SanguineBrah** [comment]
I can confirm that rolling back to ESP8266 core 2.7.4 and compiling again fixes both of the issues listed above.

**Comment by mecparts** [comment]
That's excellent news. It's not excellent that the core is slightly borked, but you know what I mean. I'll close this one out now.
