### ISSUE TITLE
Prevent Telnet server from attempting to enable (unsupported) compression

### ISSUE THREAD

**Issue by benryves** [mecparts/RetroWiFiModem#6]
I've been having a lot of fun with this project, so thank you for putting it together!

One issue I encountered was a large amount of binary data being dumped to the console when connecting to the [Discworld MUD](http://discworld.imaginary.com/lpc/index.html), i.e. after `atdt discworld.imaginary.com`.

It looks like the MUD attempts to enable [the `COMPRESS2` option](https://www.gammon.com.au/mccp/protocol.html) which the default implementation accepts but doesn't support, hence the garbled binary content instead of the plain text.

I've attached a patch which explicitly blocks attempts to use the `COMPRESS` or `COMPRESS2` options: [dont-compress.patch](https://github.com/mecparts/RetroWiFiModem/files/10985160/dont-compress.patch)

There are still issues connecting to this particular MUD but at least blocking the compression options means you have a better chance of reading what's going on. Thank you again!

**Comment by mecparts** [comment]
You can probably imagine my confusion upon first reading... COMPRESS2? I don't recognise that Telnet option... oh, it's a MUD _extension_ to Telnet!

I tried replying DONT to COMPRESS, COMPRESS2 and COMPRESS3 and it's better but still not great. There's still a great glob of text that appears after the first "Your choice: " prompt.

I turned on Telnet option display and there's about another handful of extension options that the server is sending. Replying DONT to all of those got rid of the glob of text but there's still one more gotcha. The server seems to want the client end to be in LINEMODE. That's quite literally a first for anything I've connected to (which, admittedly, consists mostly of Telnet BBSes and actual Linux Telnet servers). So there's no support whatsoever for LINEMODE in the code. Zero. And the server doesn't appear to take DONT for an answer either, at least at first blush. So there's no echo of what you type, which I could see being a problem.

Let me ponder this for a bit and see if I can't figure out how to get the server to work in DONT LINEMODE mode.

**Comment by benryves** [comment]
Thank you and sorry to open this particular can of worms, in that case!

The `LINEMODE` issue is one I'd been pondering too. If local echo was sufficient then there is the [VT102](https://vt100.net/docs/vt102-ug/chapter5.html#S5.5.2.13)/[ANSI](https://mdfs.net/Docs/Comp/Comms/ANSICodes) sequence `"\x1B[12l"` to enable local echo and `"\x1B[12h"` to disable it which may be an option if `AT$TTY` was set appropriately (rather than attempting to spoof it in the modem code).

**Comment by mecparts** [comment]
Yeah... it's a can of worms all right.
Your MUD server ignored everything I threw at it to get it to go into character mode. Literally ignored. It didn't even reply with DONTs.
I've pushed a commit to DONT all the MUD server's telopt requests. But as for linemode, feel free to fork the code and have at it for yourself. It's just such a niche case that it's not worth pursuing it any further for me.
