### ISSUE TITLE
Difference in v1 and v2 of the project?

### ISSUE THREAD

**Issue by sofakng** [mecparts/RetroWiFiModem#7]
This project looks absolutely fantastic!

I'm thinking about ordering a PCB and building one but I noticed you have an initial commit for a new version(?).

Has the PCB changed between the versions?  (do you have an extra PCB I can buy from you if you live in the US?)

Thanks!

**Comment by mecparts** [comment]
v2 went with surface mount ICs, changed from a MAX3232 to a 3237 to get the full suite of RS232 signals, and added the DFPlayer module. So, yes, the v2 PCB is different than the v1. I only ever made a couple of v1 boards, and those were by hand (iron on toner, ammonium persulfate etchant, drill with a Dremel, the whole 80s experience).

Unfortunately, I'm on the other side of the 49th parallel from the US. Believe it or not, it'd be cheaper ordering your own set of boards from JLCPCB (<$10 Cdn if you choose the cheap shipping, and it's still very quick to arrive) than it would be to try mailing one from Canada to the US.

**Comment by sofakng** [comment]
Oh, OK - No problem!

Is the BOM current from the kicad folder?

**Comment by mecparts** [comment]
It ought to be. There were no part changes between when it was generated and the gerbers were made, only a footprint adjustment on the DFplayer (I didn't double check a 3rd party footprint and of course it bit me!).

**Comment by sofakng** [comment]
Sounds good.  Thanks for such a great project!

**Comment by mecparts** [comment]
Enjoy!
