### ISSUE TITLE
Question about two RetroWiFiModem units on the same router

### ISSUE THREAD

**Issue by giobbino** [mecparts/RetroWiFiModem#9]
Hello,

First of all, thank you for sharing your amazing project! I'm delighted to find such a beautiful piece of hardware!

What I wish to do is to use two RetroWiFiModem with to my two Sergey's Micro_8088 (8088 IBM-XT clone) running MS-Dos and Windows 3.0, and connect them together with some software like Telix, etc.

Looking at your instructions, it seems to me I could connect both modems to the same router, get the IP address of both, and then call one unit from the another using the ATDT command. This should work from inside Telix, I guess?

Can you tell me if you already tried to do that? 

Next step would be to create a BBS at home (maybe using a more powerful PC as BBS server) to show young people how we spent our nights back in the 80s and why the phone bill was so high LOL

**Comment by mecparts** [comment]
I'm afraid I don't know anything about Telix but dialing one unit from another works fine for me.
